### ISSUE TITLE
Request: custom message in version string

### ISSUE THREAD

**Issue by NyaomiDEV** [EvolSoft/CustomAlerts#11]
Can you add an option to customize the version string in MCPE worlds and servers list?

**Comment by Flavius12** [comment]
Interesting! The problem is that you may see the string red if the it doesn't match the client version.

**Comment by NyaomiDEV** [comment]
What if the custom message colours itself normally (or even custom colors) when version is not compatible?

**Comment by Flavius12** [comment]
I don't know if it works. I'll try and if it works I'll add this feature. Thank you for the suggestion

**Comment by Flavius12** [comment]
https://twitter.com/shoghicp/status/632112861943361536
This will cause issues with MCPE  0.12.0 clients
