### ISSUE TITLE
Can you add more features and update to 0.12.1?

### ISSUE THREAD

**Issue by ZGamerOficial** [EvolSoft/CustomAlerts#12]
Add more features because i cant put this "&l&aStarCraft &cEconomy/PvP/Minigames/Factions coming soon! &n&b[{TOTALPLAYERS/MAXPLAYERS}]"
Can you add more space to write more in the config?because when i run the server the console throw me an error

**Comment by Flavius12** [comment]
Can you post the error message?

**Comment by ZGamerOficial** [comment]
Dont work fine in api 3.0.0 alpha5

**Comment by TheDiamondYT1** [comment]
@SoyPro Try https://github.com/EvolSoft/CustomAlerts/commit/1bd5e5975fcf16cebbba6f3c84a54bee41ea2430

**Comment by ZGamerOficial** [comment]
thanks for the fix!
