### ISSUE TITLE
full server message not working 

### ISSUE THREAD

**Issue by ghost** [EvolSoft/CustomAlerts#16]
in config.yml 
FullServer:
  custom: true
  message: "&e{PLAYER}&b, The Server is full &c[{TOTALPLAYERS}/{MAXPLAYERS}]&b!\n&l&dTry to join later :)"
but when server is full, it is not working

**Comment by Flavius12** [comment]
This may be caused from your PocketMine version. If you are running a PocketMine fork like ClearSky, ImagicalMine... the plugin may not work correctly. If you are still using the original PocketMine the plugin may be outdated for your current PocketMine version
