### ISSUE TITLE
New API Language

### ISSUE THREAD

**Issue by yungtechboy1** [EvolSoft/CustomAlerts#2]
The File: EventListener.php
The way to get the killer should be called like:
$killer = $event->getEntity()->getLastDamageCause()->getEntity();

Instead of 
Line 88: $killer = $event->getEntity()->getLastDamageCause()->getDamager();

Sorry if im wrong but im working on a plugin and ran into an issue with getting the killer and found this soloution. :+1: 
Best Of Luck!

**Comment by Flavius12** [comment]
Thanks. I will work in a small API to implement in CustomAlerts

**Comment by yungtechboy1** [comment]
Ok, Let me know if you would like any help :)

**Comment by yungtechboy1** [comment]
Never mine for another plugin I have your  method works :/ weird

**Comment by Flavius12** [comment]
API language done :+1: :D

**Comment by letsplaydev** [comment]
Yes :D
