### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ondraczsk** [EvolSoft/CustomAlerts#25]
```
10:30:50 [CRITICAL] Could not pass event 'pocketmine\event\server\DataPacketReceiveEvent' to 'CustomAlerts v1.6': Class pocketmine\network\protocol\Info not found on CustomAlerts\EventListener
10:30:50 [CRITICAL] ClassNotFoundException: "Class pocketmine\network\protocol\Info not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144
```
 on player joins
tesseract mcpe 1.1

**Comment by TheDiamondYT1** [comment]
**Short explanation:** We don't support Tesseract.

**Long explanation:** We don't support Tesseract. It is a piece of crap developed by inexperienced developers and keeps changing the API so it breaks PocketMine plugins and plugin developers have to go even further to get it to work. 

You could always use [TesseractPM](https://github.com/AppleDevelops/TesseractPM) to fix this error, or stop being a traitor and use [PocketMine-MP](https://github.com/pmmp/PocketMine-MP).

**Comment by ondraczsk** [comment]
@TheDiamondYT1 is works on 1.1 (TesseractPM) ?

**Comment by TheDiamondYT1** [comment]
Yes

**Comment by ondraczsk** [comment]
still error :D

**Comment by TheDiamondYT1** [comment]
Same error? Impossible.

**Comment by TheDiamondYT1** [comment]
Oh im so fucking dumb

**Comment by TheDiamondYT1** [comment]
Are you using the **latest master build**?

**Comment by ondraczsk** [comment]
yes

**Comment by TheDiamondYT1** [comment]
The error says otherwise

**Comment by TheDiamondYT1** [comment]
In the latest commit i fixed this

**Comment by ondraczsk** [comment]
look on pr from anyone https://github.com/EvolSoft/CustomAlerts/pull/19

**Comment by ondraczsk** [comment]
i think thats i

**Comment by ondraczsk** [comment]
it*

**Comment by TheDiamondYT1** [comment]
I've just told you [i fixed it](https://github.com/EvolSoft/CustomAlerts/commit/1bd5e5975fcf16cebbba6f3c84a54bee41ea2430).
