### ISSUE TITLE
Player data not created

### ISSUE THREAD

**Issue by kabluinc** [EvolSoft/CustomAlerts#26]
since updating to latest PMMP master branch, a player config isnt created in /data. as a result everytime a player joins, it says they joined for the first time.

**Comment by kabluinc** [comment]
Any possibility of this being looked into?

**Comment by kabluinc** [comment]
This problem still exsists in the poggit orphanage updated version

**Comment by Flavius12** [comment]
No player data file will be created. To check if a player joined for the first time the plugin uses the PocketMine API `hasPlayedBefore()` function.
See: https://github.com/EvolSoft/CustomAlerts/blob/e8cec5a042e32496134f24ae458023250d53e235/CustomAlerts/src/CustomAlerts/EventListener.php#L120
