### ISSUE TITLE
Erro spam

### ISSUE THREAD

**Issue by shukamu95** [EvolSoft/CustomAlerts#28]
INFO Notice: Undefined property: pocketmine\network\protocol\LoginPacket::$protocol1 in phar:///plugins/CustomAlerts_v1.6.phar/src/CustomAlerts/EventListener.php on line 48

https://pastebin.com/5e1dmmAQ

Genisys 0.15.10

**Comment by TheDiamondYT1** [comment]
Don't use Genisys, use PMMP
