### ISSUE TITLE
Update for 3.0.0-ALPHA8?

### ISSUE THREAD

**Issue by ghost** [EvolSoft/CustomAlerts#29]

**Comment by NML32** [comment]
It would be nice to get an update for API3 Alpha8

**Comment by TheDiamondYT1** [comment]
Ugh i'm lazy

**Comment by IwanIDev** [comment]
How about ALPHA 10 now?

**Comment by Flavius12** [comment]
I'm already working on the new CustomAlerts update. You'll have just to wait some weeks until the official release
