### ISSUE TITLE
Spams Issue on Console

### ISSUE THREAD

**Issue by xHqste** [EvolSoft/CustomAlerts#30]
29.10 15:16:34 [Server] INFO /19:16:34 [CRITICAL] ClassNotFoundException: "Class pocketmine\network\protocol\Info not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 156
-- INFO --
Running On : Leveryl 1.1 (MC:PE)

**Comment by Flavius12** [comment]
Fixed
