### ISSUE TITLE
Won't load

### ISSUE THREAD

**Issue by ghost** [EvolSoft/CustomAlerts#33]
I don't know how to fix this. XD

[15:06:48] [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\Server::getScheduler()" (EXCEPTION) in "CustomAlerts_dev-3.phar/src/CustomAlerts/CustomAlerts" at line 85

**Comment by Flavius12** [comment]
Which PocketMine version are you using? Are you running the official PMMP server software?

**Comment by ghost** [comment]
Using the jenkins .phar here: https://jenkins.pmmp.io/job/PocketMine-MP/
ALPHA-12

**Comment by Saxavlax001** [comment]
https://github.com/RevivalTeam/CustomAlerts/archive/update.zip
Use this.

**Comment by ghost** [comment]
I'll try it when I get home. : )

**Comment by Flavius12** [comment]
I will roll out the new 3.0.0 API compatible update soon
