### ISSUE TITLE
Issue with FirstJoin

### ISSUE THREAD

**Issue by TheFixerDevelopment** [EvolSoft/CustomAlerts#37]
Hey, so just recently (Since the new 3.0.0 API Update), the firstjoin setting doesn’t seem to be working. When someone first joins the server, it’ll detect the Custom MOTD setting instead of the firstjoin setting. Please fix it, as it’s getting annoying. Thanks.

**Comment by Flavius12** [comment]
Omg you're right. There is a typo on PlayerJoinEvent. Thanks for report! 👍

**Comment by Flavius12** [comment]
Fixed in v2.1!
