### ISSUE TITLE
E_ERROR

### ISSUE THREAD

**Issue by CoreCraft** [EvolSoft/CustomAlerts#8]
Error: Call to a member function hasPermission() on null
File: /src/pocketmine/Player__32bit
Line: 439
Type: E_ERROR

Code:
[430]       return $this->perm->isPermissionSet($name);
[431]   }
[432] 
[433]   /**
[434]    \* @param permission\Permission|string $name
[435]    *
[436]    \* @return bool
[437]    _/
[438]   public function hasPermission($name){
[439]       return $this->perm->hasPermission($name);
[440]   }
[441] 
[442]   /_*
[443]    \* @param Plugin $plugin
[444]    \* @param string $name
[445]    \* @param bool   $value
[446]    *
[447]    \* @return permission\PermissionAttachment
[448]    */
[449]   public function addAttachment(Plugin $plugin, $name = \null, $value = \null){

Backtrace:
#0 (): pocketmine\Server->crashDump()

PocketMine-MP version: 1.5dev #1254 [Protocol 27; API 1.12.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux localhost 3.4.67 #1 SMP PREEMPT Thu Mar 26 17:56:00 CST 2015 armv7l
PHP Version: 5.6.2
Zend version: 2.6.0
OS : Linux, android

Loaded plugins:
PopupDisplayer 2.0.1 by Heromine, Flavius12 for API(s) 1.12.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
CustomAlerts 1.5 by EvolSoft for API(s) 1.12.0
EconomyAPI 2.0.7 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomySell 2.0.5 by onebone for API(s) 1.12.0
EconomyShop 2.0.5 by onebone for API(s) 1.12.0
EssentialsPE 1.1.0 by LegendsOfMCPE Team for API(s) 1.12.0
iProtector 3.1a by LDX for API(s) 1.9.0
ItemCasePE 1.0.5 by aliuly for API(s) 1.10.0
SimpleHome 1.2 by Dutok for API(s) 1.0.0
PurePerms 1.1.5 by 64FF00 for API(s) 1.12.0
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 1.12.0
SimpleAuthHelper 1.2.3 by aliuly for API(s) 1.10.0
TapToDo 2.1.2 by Falk for API(s) 1.0.0
WorldEditArt 1.0.0_beta_dev_#048 by PEMapModder for API(s) 1.0.0
KillMoney 1.1.0 by Topic for API(s) 1.9.0
EnderPearl 1.2.3 by Yosshi999 for API(s) 1.0.0, 1.1.0
NetherChests 1.0.0 by aliuly for API(s) 1.12.0
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
FoodEffect 1.0.0 by MUedsa for API(s) 1.12.0
FloatingTexter 1.0 by Heromine/Jon for API(s) 1.12.0
KillRate 1.2.2 by aliuly for API(s) 1.10.0
PureChat 1.2.8 by 64FF00 for API(s) 1.11.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNWwtv2zi2/iuEW2DbgeX4GSeeTXGDNN2Z3WTq27jo7h0tAlqibU0kUSNKST1z+9/vdw6ph510
mnZygQ1aRDokD8/7QSq/d4ooUZ3ZYDw6nAzHR/1Bt6PyXOed2e+dYpthqHN+ff7u3dt3nW4nUcbI
NcHOZByLQgspEpUsVS5WZRoUkU7FRpq5ypPIGLy9eCkASss4xupVFNPSA5MHB5kOblSRRKk6mMdy
q/Lr69FwGRWYFgPYmY1Hx5+6nSwu11Hama1kbFS3E+hQEWHjUR+I/MIvclWUeSqeF5vIeK8ybOy9
iloEXKnixfNUJurl90A9Hg143Sd+HuKZH0YMPPjuO34b85v4TvxXJnOZiKxG5vsN4v81RR6la8HI
ed3EreOXwxqJo3CpdcwjUzdywG9H/JaVyzgKPidDS//vPP/4D/h+aBVzPe43XI8HjuvxsM31eLTH
9ZwlL547DdCUfcHsS2A82ZtAPAshnt/KuLQzDlsyGk/3ZfSwpE+LQgabRKUFrzpqy298/KD8ZBg2
q17sstK1BIsT4ftkmF1HXw2ApGF5RS4D2NrPnWd98eLlTDQG6/tXKr9VufcqyKXZvC6T7MXLzr+7
nbVKVS5jMlAME+kgbtCbhOoWtC7LKA7haMPJGHad60IHsIjZcNrtyCzimYNhr4+Za7jBrNN/5A8W
5PImjpa0pjdlDCWrZNa5iNLyo4h1IOONNoUY9ca9w6l4NhBXl3Mxf3d+fjlfiMWmFJcyF8NDMZjO
Joezfl+cXS3EsD+YCJknt1Oy3GyTAeOkd9gb4u03lYKZzhCvfTt4rU21IwD8ItMw11HYqR3ZkGzm
Oiuz15HJ2O8J4qjdG+i2pAjB9AaAyLLY6NyQXn5QuSZ1dMWbWN5GpRkMSQksy58rYQKgUrmMFYgt
8hIhJFQZSCcMGDN6VbxuAxJJ0WaPEt+/lOwCsZbE9NXi9N3i/RyAO7U0UQHayW7A5VmsZH4h1+sW
Vw2su2MWAxZci6ELBQMK364uz+bnO5z0v52RenPfvwDxLFXHxfzt1eLD23cXr9t8dDZFkZnZwQFs
cFMue4FODtp0HTTcELulKXRyGqu8MG2O2+Bdpie7LJ/f6vgKpD+Z4tpb+/4eIZ9XH7MNru/u7noK
NBH6XnFDPJ4HOtXJ9nT+Y4vDFnDfSqe7HOpULfH/nj67tQUMesP694B/j9z7yL2P3fsY798oF0eG
7ytLOWjx/R0u/sgqnHW7+Vcqju/LgqH7wph8WRhf1HZb2F/BoQE9NYuOuK/gcaOzB3gk6H8Sj6Cn
4dES9xgejUFajFBSIdC0mGyDHxWrjA0KYqFk8mQu3CbjqaLWDmuQQDRH/lVBodvppwVscw8vlHvM
v/7nDrfH384sUPl+s/F+pnk8t6//6TGnLSbA54+FSs6kUTt6bgF3tXzPlmUclfF2V7N/IhlZdOAX
BAQgIFOP4tdZ7VWUZLH6QSeqxUsL2OIFoXSHj9dloW+eKqU2W6IQbG//CB7mZa6osG1nywa273N7
2jgcv3nT7z+Zn11bfKi0KwJaj1/OlnsGyCttjXfQYKnVdgo27qmNgbtMT/ervDmX3Zeo82yUAT8b
vd5EQfZkgmiIqRTqCPtKCdSUHrSw7EjgBxVnOxXvvaFdaQx7oz/vkG1hP8I5N0zI1zjmQmYL/Vq3
2Kogu6lywI1Di5s3Mn4yryxkVuhQ+36z9yNI/6DzODwPo+I0L1r074D3Y2T/eqkKeY2m7vpZH93o
rrmeX8rsUoeUs56Is0wlMksYpe/fEWUKlMm88P09Or82abSIPbhKZBx7/3PmVU5c5EodJNIUGNzZ
B2L7RxTHlyhEti2ZNbAvlA4LnUXBU+XPelffbxPwmCIoBdtzNDM7tWwD/IIn/ksbs4mOj48/W9l/
a/lTk/A1PviTKjYqP9sos9OJ7YDvGfKXY8vwzyf7VAW0/dcw81rdLjSasBYjNWjPuO5xsZ8v2uyM
vr1/qvb3/RYl35wfahxg9o3W4flqhZKtxW4L+AWtXb5XoZFPprVmY6uws1ga85jQ4prnQBYIGNte
kDJvWFZE6XqhPhY7eW9vYI/Hh895Dv6O8Sfjc4cA308ebZwUZt7JQu2FPgbtx4zh/0M5XVm4i3SX
0E90q1wP2OnuHk38TcfhVRF27rvlDWjOQfM3dxwyVr/w+R4Qtk7zveyB/FELyJXAZxtZ7FXADNqX
39GXC+AvRdpWeX1flG8kHxcb9EydzxTGRFfz9KfLYkbyic5D6YBcQTiVkvlIuZflGtVXESk6Pn02
r9/EmU5X0VrQFYqf++mzN3kk/l7GYtAX/aPZ8Gg2GIr3izM+s6UJFp9HEj6hmBPkclXMBJp1e3jd
mpPpvDgZHA9GQwKusQLVhjrp01siP3r2ENScjBhiMnmXepntMiG8k8Ehge82kEEcmeJEr1YEsBrx
fi0RDk502gLlsNBqVqhMkEcZI7KEiQQNvygN3Sw0IdO7nDM5ughP/LLfl9Op/RW/emUfjs50ruzj
8oyYddP++lfhnn62v1e/L94uTi/mF6f/On939ckN/rslELr2Okl1jpKIN4U88q0XR0kEOQ2PLgmI
uFh4ZRbCqiteZJrqMg2UE5gng02kbhVdQZhqzm2k7rwQYpKYeDJgiaLw0nfeKo7Wm8JJygpZphFI
MDuwRC8rwEbmYQCmK9zZbeZGwmi1ioIyLrYnA9YpX0wUOveMKijsmRPmAdTF1kS4rmxgRqmwNYUF
8ubidEEgUl8vQ9jBmvDkO/4BE2ixPSNvlSOB7cFjg2AmVzqHZGrjciTTzUEdOnrbJCarFxSRRMAG
X4JsutAhuxfAsWcS6TOxQHWhRMWXkLkSqHkEwqPBgyxEQHopxFKJKA3iEtUzHsQ9fyNcV2jkhV4R
gn2cRq5UV2gqpwyhFMtcyRux1WXucIloJcBbtIp4B2gmh4cg1gLxT+quRncQqpWEboy40+lfCiGz
DNWeIAEmYDaAOWzp0pRu9izfdxuVijJb5zIEgp6fkqVaZDM/Fc8WG8RaL1aUekUs03Up10rQXSmL
zFm1ifDOV0HRbyxUWorSMHBc7C6kS0gXzlTau4tuogxth+zpfH1AbwcXUO21Xl3/ePX2+nB07A2v
aR3EWCOaCR9xee13aKMPGy5F6crYIPwKuj6294dQUy5TE8OTQjvM0mRKQQeeVMEqRccVBUpskHVi
VnICxNaumi35ohhwsymLUJPD2CtrIsYFmCDWRoWWrFPyPUFmSvHG5S5xG0nx3xS4MIUDWJXVZoLy
Cy282mCdJCs1GtS4XayqpEOEKAYjRC6CITB3SMqYiXwWkpyaAQ9kLUFUg/6cQ2WFBxwL8nQBc4VF
EKnLrXB2hOkusNajjRiefUDqhTJhUjIMRa6MtTwiE7Z2A3KkQV6iICVgb0tF8oDQ1a+l5Av+NaqL
VNgb0hduS2SZl0Bu90NAV5RCPGhzvVb5DKO0808lfxcAdzo12zRYSHMDi89v4EA9Gn8PJbB9VkzS
rE2O6qWESWC26QoOS8KFL5hsF2JIIDW+F2axIPsSLClTeA5NYdxXbDLgB86V648Io0hOW2KHTT2t
SSOpWnJ+XJGH8icN8MSuiIq/0BcOOa8KFWU7tsK9teIFOICexZAkwjx4jssZYyJvtRmEffVvsV5C
sFSICAsWnFgoJiVqLZfbAgSJK0tKnzePDKnXejp4uouYMBa2oNThEpQDGZbLKoK5IEwhfqeMaoUY
Ue1o1b+hNEtGu9bgQ5NrkMywz5qJtBlvJiaDoc/BguNygWAjw/9wBqiSq8gfkTnS3qgCI83Bnyzf
EM6Aw59DWlv3AJYAxw5JozzDo0rZ2jUHTZ0iXMAfQCP54udYsKQjE8YcT8mz7DSf0xvhgK03fmOd
n3Z4Sw5L+YSn9+5PJl91NS9knamA0o5hkRCtVhl2bc0A4q3KTMPmqO/4NC8fJMhxPbJcr2W+hKy9
QMexrfzInh+UKquOSHFrhFujqbhLS05wbSqQ/EsYzctu5YF7VuPMxkYxbk4Ze9KYY0+8tdmF3wyi
vy7jsCYkgr/epaIhnWyEvjYB5WDwsN+3PIpnb9jq7kUithW7umZqhba0Cmi01o177RjQ0imYcKrb
N4UH7Ke1jirwYFOmN8bK+4KdjcIPA4kyakmIG2ELzy67Qo50b+wkjzIuVQ4NLkJVqdn5yfGho/O1
tsv21Uchl+oSu6yNwe7ipj0Bzxz2vUDSyRFz7Wyh2ogG6lz5h6j8NFUF6aIulGAasc07S1mgQqe0
L6mmRLqBPbnwxQ5oy0A3aqPWUtUZCCVElWmcxVYj5Pj5tiDcXeENWsZMmYa39YqKFISVyaGNKk1m
47Kb0kpoQ51ToF0LoKOpJ35A0wDxnqDyhOGezd93sRYULBF/7qKw2NgIyf5do/cY/UxMXRpuErRh
wbSm9sRpCH/ayHh1gJLa1gyhgp25jbCltT+dth2yzoUtXK2q5PwjOR8VHTLuWsemjT9EKWo2sAWz
UWzalFnfz9N5lZebCplKDlp0hy7Ip/I4zTz32q6AqMVcluuZS/GvxIBSu1WmoRqOh6v6zXAc26iq
rvOdKmZi0FRlRhygfytKGMzBOrCiRVwLTWvTqo3aqdJVVbIR3eDE9ic81ZkXscsKDyDEgi3MLfHs
kplIMLR21TsY4vMOIveWPnKxQUnu4EfkpP6naG0PYRb3qWEfZdU9++nt4nwmOOriX1CilUnRyjAi
vk0i1TF5bueavFrFpzvaClC1I5I4XtmKOCWBErKagixn2HcphEKZzUxkRtRYEtylI+f1u+AqhtnK
84rclRhcSqNam70YwFEe2KUrhhgYPDSgiqD3kp3WqDYVbA4LwkyNjDshEQqBye5Hqd9qklvGppek
QMA9B1UqFA5kfCe3xuJ2eFp2tBO/2YxOE12m7QRgXH1UEUHkEzafv6dkxDMx/vxSmQMaWtrd9247
WUcMjocPrmbrSpXt2pbKYluqFUUiPqygiEVqqLHaI4xW6LOR70reIulS4xdRc6qo2cm2rhF3uagu
aDhQrPhcsQqLLoytypinaQNT9chFo8CmEm54cup+YRhAW4nqF019h/UNQ9+E0rfQZNSUYGr+95RB
Aq2UcSk/CrkvF3QcAeeHxh52dcFG+g7NfGlay5wepKOOndQudXZH81GtUEyioyJ3+tQQiMZWSbsJ
H7w0WdAS3rRRFe29+8S7+HcnI+6I0f2WyunXrWe3Z7hnoKyZOPombJnOythhc8+UmvYQ+yn7pAfp
EdH2RMxjOzIkSRJlglhd0AGHgw5ceKDTqJmwxV2lUkgoLTMUO7biswbJwcMWGg4XsExplduQkE7o
9U7SRjWQYTJZRrB8O8UdhNmOeGaDETXv9KGwsFCbY52RWOt1lXwd3MiuPTpO2YXU6WQHmm2yKF3p
xgzoS9+Z3bLXOl1DIcT0pTrdJlTms4cYyNfUhFLf4oZFM8wEw9akkOs1so9rxetDDqoR6XPpm4e5
sfQQOvMQPSQva8qs4v3VsAk7OrMKyFPPJeemAmSozlrHM2d0QsdHRirWGWWrrqBrezraACWuFENl
skKlrCBs5KeU8jxNcqnVnkHLNhLh7idaNUSJgtMUNsFVAc9hIw3Z4Qq/2RMKXZk9IJI4QrqxWjn/
KCnf2hcqWIDfETGrqOEhGLspNEz7Z3r0JH3YToB/E0YbBasypH22yUxU/YJt2qrDYu7GHjoq5eaW
s5jhioHYTlBIRCDUpfgW6bwrE8BPgs6WyXU5JTW7zQQdMM+G30+7k+OPg+7o46g7/H7wfYhMbKPW
C7pSCijCnBz1xRr2bezbePKSj5LpLi8lgfDNMd0HtD5YD/nOrn5FOljXf1aSBTTVvZhf46hQI/s1
vWe/3f/Nfl5vP9RdBqhrNs3fpMgYniPzBmD/bKZ6K+kLA/eyimK+CAXqgb3oXBVZPbpOmucNvLe+
Df3F1Fdi9HlUsrQnp/Vk1ITbrGg4KCQRFLbYvZpf8K70nAWo5Zq1WzDM3/K7JzGhb+0HxLnw6D5p
2J/0R3h8/iP0thpNR0pOwnAyGR1NDwfj/qE86g+Hcrw8kqPpeDw4Wg7HfSWeY6f5hsTCX8nyxtpE
Hxuhu2a9+rqfGH2nVq7TBJT3O1KTVSBRqY6xbX81nQbTo6PDyQRbj46HIzXqL4+nx2HI+5lNohsR
GnYss8tpZIWPyYW+USnyTF5DPih5g4hgBcVf320lX0nQBx004bcoq/5OY9z59On/AGYPBoo=
===END CRASH DUMP===

**Comment by Flavius12** [comment]
Are you sure this bug is related to CustomAlerts? In the crash dump you posted there isn't any reference to CustomAlerts plugin

**Comment by Flavius12** [comment]
The bug seems not related to CustomAlerts. However try with v1.6 :)
