### ISSUE TITLE
There is a problem

### ISSUE THREAD

**Issue by ZGamerOficial** [EvolSoft/CustomAlerts#9]
Why when a playera join my server nothing appear?before yes but now not?can you help me please?

**Comment by Flavius12** [comment]
Can you be more detailed? Do you have additional slots? What happens exactly?

**Comment by ZGamerOficial** [comment]
sorry players when enter yes but when i enter no

**Comment by Flavius12** [comment]
The Full server message must be disabled if you have additional/vip slots. You have to set FullServerMessage to false. Let me know if it works

**Comment by ZGamerOficial** [comment]
Yes now yes it works.Good job!

**Comment by Flavius12** [comment]
Thank you! :D
